from stock.cleaning.cleanDB import cleanFinancial

#cleanFinancial("GoogleAnnualIncomeStatements")
#cleanFinancial("GoogleAnnualBalanceSheets")
#cleanFinancial("GoogleAnnualCashFlowStatements")
#cleanFinancial("GoogleQuarterlyIncomeStatements")
#cleanFinancial("GoogleQuarterlyBalanceSheets")
#cleanFinancial("GoogleQuarterlyCashFlowStatements")
#cleanFinancial("BloombergAnnualIncomeStatements")
#cleanFinancial("BloombergAnnualCashFlowStatements")
cleanFinancial("BloombergAnnualBalanceSheets")
#cleanFinancial("BloombergQuarterlyIncomeStatements")
#cleanFinancial("BloombergQuarterlyCashFlowStatements")
#cleanFinancial("BloombergQuarterlyBalanaceSheets")
cleanFinancial("YahooAnnualIncomeStatements")
cleanFinancial("YahooAnnualBalanceSheets")
cleanFinancial("YahooAnnualCashFlowStatements")
#cleanFinancial("YahooQuarterlyIncomeStatements")
#cleanFinancial("YahooQuarterlyBalanceSheets")
#cleanFinancial("YahooQuarterlyCashFlowStatements")
cleanFinancial("NasdaqAnnualIncomeStatements")
cleanFinancial("NasdaqAnnualBalanceSheets")
cleanFinancial("NasdaqAnnualCashFlowStatements")
#cleanFinancial("NasdaqQuarterlyIncomeStatements")
#cleanFinancial("NasdaqQuarterlyBalanceSheets")
#cleanFinancial("NasdaqQuarterlyCashFlowStatements")
