ID = "id"
DATE = "date"
CASH_BALANCE = "cash_balance"
SHORT_TERM_INVESTMENTS = "short_term_investments"
ACCOUNTS_RECEIVABLE = "accounts_receivable"
INVENTORY = "inventory"
CURRENT_ASSETS = "current_assets"
PROPERTY_PLANT_EQUIPMENT = "property_plant_equipment"
ACCUMULATED_DEPRECIATION = "accumulated_depreciation"
GOODWILL = "goodwill"
INTANGIBLES = "intangibles"
LONG_TERM_INVESTMENTS = "long_term_investments"
TOTAL_ASSETS = "total_assets"
ACCOUNTS_PAYABLE = "accounts_payable"
NOTES_PAYABLE = "notes_payable"
CURRENT_PORTION_OF_DEBT = "debt_current_portion"
CURRENT_LIABILITIES = "current_liabilities"
LONG_TERM_DEBT = "long_term_debt"
DEBT = "debt"
OTHER_LIABILITY = "other_liability"
TOTAL_LIABILITY = "total_liabilities"
PAID_IN_CAPITAL = "paid_in_capital"
PREFERRED_STOCK = "preferred_stock"
RETAINED_EARNINGS = "retained_earnings"
TREASURY_STOCK = "treasury_stock"
TOTAL_EQUITY = "total_equity"


REVENUE = "revenue"
COST_OF_REVENUE = "cost_of_revenue"
GROSS_PROFIT = "gross_profit"
SELLING_ADMIN_EXPENSE = "selling_admin_expense"
R_AND_D = "r_and_d"
DEPRECIATION_INCOME = "depreciation_income"
INTEREST_EXPENSE = "interest_expense"
UNUSUAL_EXPENSE = "unusual_expense"
OPERATING_EXPENSE = "operating_expense"
OPERATING_INCOME = "operating_income"
GAIN_ON_ASSETS = "gain_on_assets"
INCOME_BEFORE_TAX = "income_before_tax"
INCOME_AFTER_TAX = "income_after_tax"
MINORITY_INTEREST = "minority_interest"
AFFILIATES = "affiliates"
OTHER_ITEMS = "other_items"
NET_INCOME = "net_income"
PREFERRED_DIVIDENDS = "preferred_dividends"




NET_INCOME_CASH_FLOW = "net_income_cash_flow"
DEPRECIATION_CASH_FLOW = "depreciation_cash_flow"
AMORTIZATION = "amortization"
DEFERRED_TAXES = "deferred_taxes"
NON_CASH_ITEMS = "non_cash_items"
WORKING_CAPITAL = "working_capital"
CASH_OPERATING = "cash_operating"
CAPITAL_EXPENDITURES = "capital_expenditures"
OTHER_INVESTMENTS = "other_investment"
CASH_INVESTING = "cash_investing"
FINANCING_ITEMS = "financing_items"
DIVIDENDS = "dividends"
CASH_STOCK =  "cash_from_stock"
CASH_DEBT = "cash_from_debt"
CASH_FINANCING = "cash_financing"
NET_CHANGE_IN_CASH = "net_change_in_cash"
CASH_INTEREST_PAID = "cash_interst_paid"
CASH_TAXES_PAID = "cash_taxes_paid"