from scrapy import Item,Field
class IncomeItem(Item):
	Symbol=Field()
	Date=Field()
	TotalRevenue = Field()
	CostofRevenue = Field()
	GrossProfit = Field()
	OperatingExpenses = Field()
	ResearchandDevelopment = Field()
	SalesGeneralandAdmin = Field()
	NonRecurringItems = Field()
	OtherOperatingItems = Field()
	OperatingIncome = Field()
	Addlincomeexpenseitems = Field()
	EarningsBeforeInterestandTax = Field()
	InterestExpense = Field()
	EarningsBeforeTax = Field()
	IncomeTax = Field()
	MinorityInterest = Field()
	EquityEarningsLossUnconsolidatedSubsidiary = Field()
	NetIncomeContOperations = Field()
	NetIncome = Field()
	NetIncomeApplicabletoCommonShareholders = Field()
